urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()
urlpatterns = patterns('',
    url(r'^yadis/$', 'server.views.serveryadis'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', {"template_name": "users/login.html"}),
    url(r'^accept/$', 'users.views.accept'),
    url(r'^(?P<uid>[^/]+)/yadis/$', 'users.views.useryadis'),
    url(r'^(?P<uid>[^/]+)/foaf/$', 'users.views.userfoaf'),

    url(r'^(?P<uid>[^/]+)/profile$', 'users.views.userpage'),
    url(r'^(?P<uid>[^/]+)/$', 'users.views.userpage_short', name="user_entrypoint"),
    url(r'^$', 'server.views.endpoint'),
)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.urlresolvers import reverse as urlreverse
import datetime
from microidutils import microid, find_microid
from django.core.signals import *
from django.db.models.signals import post_save

#Represent one trusted root URI. Can be shared between several users.
class TrustedRoot(models.Model):
	root = models.URLField("Trusted root URI", primary_key = True)

	def __str__(self):
		return self.root

#Represent one system user, based on Django's internal user system.
class DjangoidUser(models.Model):
	djangouser = models.ForeignKey(User, unique=True)
	trusted_roots = models.ManyToManyField(TrustedRoot, blank = True, null = True, help_text = "URI's trusted by this user")

	def __str__(self):
		return self.djangouser.username

	def authenticate(self, root):
		r = TrustedRoot.objects.filter(root = root)
		if len(r) == 0: #Certainly not trusted
			TrustedRoot(root = root).save()
		else:
			for mr in self.trusted_roots.all():
				if root == mr.root:
					return True
		return False

	def get_djangouser(self):
		return User.objects.get(username = self.djangouser)

	def get_user_page(self):
		#Strip of last / from BASE_URL
		return settings.BASE_URL[:-1] + urlreverse("users.views.userpage", kwargs = {"uid": str(self.djangouser)})

	def get_yadis_uri(self):
		return settings.BASE_URL[:-1] + urlreverse("users.views.useryadis", kwargs = {"uid": str(self.djangouser)})

	def get_name(self):
		"""
		Get a (public) representation of the full name of a user

		>>> user = DjangoidUser(djangouser = "test")
		>>> user.get_name()
		'test'
		"""
		f = None
		l = None
		try:
			f = UserAttribute.objects.get(user = self, attribute__name__exact = "FIRST_NAME", public = True).value
		except:
			pass
		try:
			l = UserAttribute.objects.get(user = self, attribute__name__exact = "LAST_NAME", public = True).value
		except:
			pass

		if l is None and f is None:
			return self.djangouser
		else:
			if l is None:
				return f
			if f is None:
				return l
			return f + " " + l

	def get_attributes(self, public = False, area = ""):
		attributes = []
		atts = UserAttribute.objects.filter(user = self, public = public)
		if area == "FOAF": 
			for a in atts.filter(attribute__foaf_attribute=True):
				attribute = {}
				attribute["title"] = a.attribute.foaf_name
				attribute["value"] = a.value
				attribute['protocol'] = a.attribute.protocol
				attributes.append(attribute)
			return attributes
		elif area == "openid":
			for a in atts.filter(attribute__openid_attribute=True):
				attributes[a.attribute.ax_name] = a.value
			return attributes
		else:
			for a in atts:
				attribute = {}
                                attribute["title"] = a.attribute.title
                                attribute["value"] = a.value
                                attribute['protocol'] = a.attribute.protocol
                                attributes.append(attribute)
			return attributes


	def get_foaf(self):
		import sha
		try:
			from rdflib.Graph import Graph
			from rdflib import URIRef, Literal, BNode, Namespace, URIRef
			from rdflib import RDF
		except ImportError:
			raise Exception, "Please install RDFLib from http://rdflib.net"

		FOAF_NS = "http://xmlns.com/foaf/0.1/"

		store = Graph()
		store.bind("foaf", FOAF_NS)
		FOAF = Namespace(FOAF_NS)

		user = BNode()
		store.add((user, RDF.type, FOAF["Person"]))
		for (k,v) in self.get_attributes(True, "FOAF").items():
			store.add((user, FOAF[k], Literal(v)))
		#store.add((user, FOAF["family_name"], Literal(attributes["LAST_NAME"])))
		#store.add((user, FOAF["nick"], Literal(attributes["NICKNAME"])))
		#store.add((user, FOAF["homepage"], URIRef(attributes["HOMEPAGE_URI"])))
		#store.add((user, FOAF["mbox_sha1sum"], Literal(sha.new(attributes["EMAIL"]).hexdigest())))
		#store.add((user, FOAF["jabberID"], Literal(attributes["IM_JID"])))
		return store

def createDJIDUser(sender, instance, **kwargs):
	DjangoidUser.objects.get_or_create(djangouser=instance)

post_save.connect(createDJIDUser, sender = User)
	

#Identities can have attributes. These items represent one possible attribute.
class IdentityAttribute(models.Model):
	name = models.CharField("Name", max_length = 128, help_text = "Internal name of the attribute.")

	ax_name = models.TextField(blank = True, null=True)
	foaf_name = models.TextField(blank = True, null=True)
	namespace = models.TextField(blank=True, null=True)

	openid_attribute = models.BooleanField(default=False)
	foaf_attribute = models.BooleanField(default=False)

	title = models.CharField("Title", max_length = 128, help_text = "Title of the attribute, as displayed to the user")
	description = models.TextField("Description", blank = True, help_text = "Longer description of the attribute, as displayed to the user")
	protocol = models.TextField(null=True, blank=True)
	regex = models.CharField("Validation regex", max_length = 128, blank = True, help_text = "Regex the value of this field is validated upon on updates")

	def __str__(self):
		return self.title

#This maps an attribute to a user, including a value, obviously
class UserAttribute(models.Model):
	user = models.ForeignKey(DjangoidUser, help_text = "DjangoidUser this attribute value belongs to")
	attribute = models.ForeignKey(IdentityAttribute, help_text = "Attribute of which this is the value for this user")
	value = models.TextField("Value")
	#True if this attribute's value may be displayed to all trust roots
	public = models.BooleanField("Public", help_text = "If this is true, this attribute is returned in all authentication requests, of all trust roots")
	#List of specific trust roots this attribute may be displayed to.
	#If "public" is True, this got no meaning at all
	public_for = models.ManyToManyField(TrustedRoot, blank = True, null = True, help_text = "List of all trust roots this value should be displayed to. If \"public\" is true, this list got no value")

	def __str__(self):
		return str(self.user) + ": " + str(self.attribute)


	#class Meta:
		#Only store an attribute once for every user
	#	unique_together = (("user", "attribute"),)

#A claimed webpage. This will be checked using MicroID
class ClaimedUri(models.Model):
	user = models.ForeignKey(DjangoidUser)
	uri = models.URLField()
	description = models.TextField(blank = True)
	last_checked = models.DateTimeField(default = datetime.datetime(2006, 1, 1))
	is_valid = models.BooleanField(default = False)

	def __str__(self):
		return self.uri

	def get_contact_uri(self):
		return self.user.get_user_page()

	def get_microids(self):
		return [microid(self.get_contact_uri(), self.uri), microid("mailto:" + self.user.get_djangouser().email, self.uri)]

	def update_validity(self):
		found = find_microid(self.uri)
		self.last_checked = datetime.datetime.now()
		self.is_valid = False
		for id in self.get_microids():
			if id in found:
				self.is_valid = True
		self.save()

	class Meta:
		unique_together = (("user", "uri"),)
		get_latest_by = "last_checked"
		ordering = ["user", "is_valid", "last_checked"]

users/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseForbidden
from django.conf import settings
from django.core.urlresolvers import reverse as urlreverse
from openid.server import server
from django.contrib.auth.models import User
from server.views import getDjangoidUserFromIdentity
from users.models import TrustedRoot, DjangoidUser, UserAttribute
from openidhandlers import convertToOpenIDRequest, checkYadisRequest, convertToHttpResponse
from microidutils import microid
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

def useryadis(request, uid):
	uid = User.objects.get(username = uid)
	res = render_to_response("users/yadis.xrds", {"server_url": settings.BASE_URL[:-1] + urlreverse("server.views.endpoint"), "uid": uid})
	mimetype = "application/xrds+xml; charset=%s" % settings.DEFAULT_CHARSET
	res["Content-Type"] = mimetype
	return res

def userpage_short(request, uid):
	uid = User.objects.get(username = uid)
	#Check whether this is a YADIS request
	if checkYadisRequest(request):
		return useryadis(request, uid.username)

	user = DjangoidUser.objects.get(djangouser = uid)
	user.attri\butes = user.get_attributes(True)
	mid = microid(user.get_user_page(), user.get_user_page())
	res = render_to_response("users/userpage.html", {"server_url": settings.BASE_URL[:-1] + urlreverse("server.views.endpoint"), "user": user, "microid": mid})
	res["X-XRDS-Location"] = user.get_yadis_uri()
	return res

@login_required
def userpage(request, uid):
	if request.user.username == uid:
		uid = User.objects.get(username = uid)
		user = DjangoidUser.objects.get(djangouser = uid)
		user.attributes = user.get_attributes(True)
		mid = microid(user.get_user_page(), user.get_user_page())
		res = render_to_response("users/userpage.html", {"server_url": settings.BASE_URL[:-1] + urlreverse("server.views.endpoint"), "user": user, "microid": mid})
		res["X-XRDS-Location"] = user.get_yadis_uri()
		return res
	else: 
		#return only public data, but as a demo it still works
		return HttpResponseForbidden()

@login_required
@csrf_exempt
def accept(request):
	r = convertToOpenIDRequest(request)

	if r is None:
		return HttpResponse("Nothing here")

	if request.method == "GET":
		return render_to_response("users/accept_root.html", {"openid_request": r})

	if request.method == "POST":
		if request.POST.has_key("cancel"):
			return convertToHttpResponse(r.answer(False))
		if request.POST.has_key("remember"):
			user = getDjangoidUserFromIdentity(r.identity)
			root = TrustedRoot.objects.get(root = r.trust_root)
			user.trusted_roots.add(root)
		return convertToHttpResponse(r.answer(True))

def userfoaf(request, uid):
	uid = User.objects.get(username = uid)
	user = DjangoidUser.objects.get(djangouser = uid)
	return HttpResponse(user.get_foaf().serialize(format = "pretty-xml"))

templates/users/accept_root.html
{% extends "base.html" %}
{% block "title" %}Accept authentication request{% endblock %}
{% block "body" %}
                We got a request from {{ openid_request.trust_root|escape }} to authenticate you as {{ openid_request.identity|escape }}.<br />
                If you accept this, you will be redirected to {{ openid_request.return_to|escape }}.<br />
                If you press cancel, you will be returned to {{ openid_request.getCancelURL|escape }}.<br />

                <form method="post" action="">
                        {% if openid_request.trustRootValid %}
                        <input type="checkbox" name="remember" checked="yes" value="yes" /> Remember
                        {% endif %}
                        <input type="submit" name="yes" value="yes" />
                        <input type="submit" name="cancel" value="Cancel" />
			<!--{% csrf_token %}-->
                </form>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% block "title" %}Login{% endblock %}
{% block "body" %}
{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}
<div>Please provide login credentials to login at <span id="trust_root"></span></div>
<form action="{{ app_path }}" method="post" id="login-form">
  <div>
    <label for="id_username">Username:</label> <input type="text" name="username" id="id_username" />
  </div>
  <div>
    <label for="id_password">Password:</label> <input type="password" name="password" id="id_password" />
    <input type="hidden" name="this_is_the_login_form" value="1" />
    <input type="hidden" name="post_data" value="{{ post_data }}" /> 
  </div>
  <div>
    <label>&nbsp;</label><input type="submit" value="Log in" />
  </div>
  {% csrf_token %}
</form>

<script type="text/javascript">
        document.getElementById('id_username').focus();

        function gup(name)
        {
                var regexS = "[\\?&]"+name+"=([^&#]*)";
                var regex = new RegExp( regexS );
                var tmpURL = window.location.href;
                var results = regex.exec( tmpURL );
                if( results == null )
                        return "";
                else
                        return results[1];
        }
        document.getElementById('trust_root').innerHTML = unescape(gup("tr"));
</script>
{% endblock %}

templates/users/userpage.html
{% extends "base.html" %}
{% block "title" %}User page of {{ user.get_name }}{% endblock %}
{% block "extrahead" %}
		<link rel="openid.server" href="{{ server_url }}" />
		<link rel="openid.delegate" href="{{ user.get_user_page }}/" />
		<meta http-equiv="x-xrds-location" content="{{ user.get_yadis_uri }}" />
		<meta name="microid" content="{{ microid }}" />
{% endblock %}
{% block "body" %}
		<h1>User page of {{ user.get_name }}</h1>
		<h2>About {{ user.get_name }}</h2>
		<div class="vcard">
			{% for attr in user.attributes %}
			<div>{{attr.title}}<span class="fn"><span class="given-name">{{ user.attributes.FIRST_NAME }}</span>{% if user.attributes.LAST_NAME %} <span class="family-name">{{ user.attributes.LAST_NAME }}</span>{% endif %}</span></div>
{% endfor %}
			{% if user.attributes.HOMEPAGE_URI %}
			<div>Homepage: <a class="url" href="{{ user.attributes.HOMEPAGE_URI }}">{{ user.attributes.HOMEPAGE_URI }}</a></div>
			{% endif %}
			{% if user.attributes.EMAIL %}
			<div>Email: <a class="email" href="mailto:{{ user.attributes.EMAIL }}">{{ user.attributes.EMAIL }}</a></div>
			{% endif %}
			{% if user.attributes.IM_JID %}
			<div>Jabber: <a class="url jid" href="xmpp:{{ user.attributes.IM_JID }}">{{ user.attributes.IM_JID }}</a></div>
			{% endif %}
			{% if user.attributes.NICKNAME %}
			<div>Nick: <span class="nickname">{{ user.attributes.NICKNAME }}</span></div>
			{% endif %}
			{% if user.attributes.DATE_OF_BIRTH %}
			<div>Date of birth: <abbr class="bday" title="{{ user.attributes.DATE_OF_BIRTH }}">{{ user.attributes.DATE_OF_BIRTH }}</abbr></div>
			{% endif %}
		</div>
		<h2>Claimed URIs</h2>
		<table>
			<thead>
				<tr>
					<th>URI</th>
					<th>Valid</th>
					<th>Last check</th>
					<th>MicroID</th>
				</tr>
			</thead>
			<tbody>
				{% for uri in user.claimeduri_set.all %}
				<tr>
					<td><a href="{{ uri.uri }}" rel="me">{{ uri.uri }}</a></td>
					<td>{{ uri.is_valid }}</td>
					<td>{{ uri.last_checked }}</td>
					<td>{{ uri.get_microids }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
{% endblock %}